context:
  version: "2.17.3"

package:
  name: remix
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-remix/-/create-remix-${{ version }}.tgz
  sha256: e029cd1373116d216672940625f47d1601816c3835fd80946dedc9310031d870

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-remix --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Build Better Websites. Create modern, resilient user experiences with web fundamentals.
  homepage: https://github.com/remix-run/remix
  repository: https://github.com/remix-run/remix

extra:
  recipe-maintainers:
    - danielnachun
