context:
  version: "2.16.4"

package:
  name: remix
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-remix/-/create-remix-${{ version }}.tgz
  sha256: 3b5f5583ee5774c7f419d9ff1d95fa37c8edbd43bc9b759b4729428882a0d114

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-remix --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Build Better Websites. Create modern, resilient user experiences with web fundamentals.
  homepage: https://github.com/remix-run/remix
  repository: https://github.com/remix-run/remix

extra:
  recipe-maintainers:
    - danielnachun
