context:
  version: "2.16.6"

package:
  name: remix
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-remix/-/create-remix-${{ version }}.tgz
  sha256: 345b8012cb9f3a71e2fbd70cb083fb656d4844652acacfc52c476dc4576220cc

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-remix --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Build Better Websites. Create modern, resilient user experiences with web fundamentals.
  homepage: https://github.com/remix-run/remix
  repository: https://github.com/remix-run/remix

extra:
  recipe-maintainers:
    - danielnachun
