context:
  version: "2.15.3"

package:
  name: remix
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-remix/-/create-remix-${{ version }}.tgz
  sha256: 3d3d2caa67156f31036f657a64b3a9b94fa61c511cd591830395d01b9539d637

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-remix --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Build Better Websites. Create modern, resilient user experiences with web fundamentals.
  homepage: https://github.com/remix-run/remix
  repository: https://github.com/remix-run/remix

extra:
  recipe-maintainers:
    - danielnachun
