context:
  version: "2.16.3"

package:
  name: remix
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/create-remix/-/create-remix-${{ version }}.tgz
  sha256: e2ac6954e3390c24562cb7f8454529b60fc53d2b33a5139feef327bf563509c2

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - create-remix --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: Build Better Websites. Create modern, resilient user experiences with web fundamentals.
  homepage: https://github.com/remix-run/remix
  repository: https://github.com/remix-run/remix

extra:
  recipe-maintainers:
    - danielnachun
